include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Mantener solo algunos errores críticos en analyzer
    dead_null_aware_expression: warning
    avoid_print: info
    duplicate_ignore: warning
    dead_code: warning
    unused_local_variable: warning
    unused_import: warning
    sized_box_for_whitespace: warning

linter:
  rules:
    - unnecessary_statements
    - use_build_context_synchronously
    - deprecated_member_use_from_same_package
    - directives_ordering
    - sized_box_for_whitespace
    - prefer_foreach
    - sort_child_properties_last
    - prefer_single_quotes
    - prefer_final_locals
    - avoid_unused_constructor_parameters
    - avoid_empty_else
    - always_declare_return_types
    - avoid_classes_with_only_static_members
    - prefer_constructors_over_static_methods
    - avoid_function_literals_in_foreach_calls
    - avoid_redundant_argument_values
    - prefer_const_declarations
    - prefer_final_fields
    - unawaited_futures