include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - lib/generated_plugin_registrant.dart
    - unused_import: warning
    - unused_local_variable: warning
    - dead_code: warning
    - prefer_null_aware_method_calls: warning
    - prefer_null_aware_operators: warning
    - unnecessary_null_aware_assignments: warning
    - unnecessary_nullable_for_final_variable_declarations: warning
    - use_super_parameters: warning
    - dead_code: warning
    - avoid_duplicate_case_values: warning
    - avoid_unused_constructor_parameters: warning
    - unnecessary_this: warning
    - unnecessary_lambdas: warning
    - prefer_const_constructors_in_immutables: warning
    - prefer_const_literals_to_create_immutables: warning
    - prefer_const_constructors: warning
    - prefer_const_literals_to_create_immutables: warning
    - prefer_const_constructors: warning
    

linter:
  rules:
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - always_use_package_imports
    - annotate_overrides
    - avoid_annotating_with_dynamic
    - avoid_double_and_int_checks
    - avoid_empty_else
    - avoid_function_literals_in_foreach_calls
    - avoid_init_to_null
    - avoid_null_checks_in_equality_operators
    - avoid_positional_boolean_parameters
    - avoid_print
    - avoid_redundant_argument_values
    - avoid_relative_lib_imports
    - avoid_returning_null_for_void
    - avoid_setters_without_getters
    - avoid_types_as_parameter_names
    - avoid_unnecessary_containers
    - camel_case_types
    - cancel_subscriptions
    - cascade_invocations
    - close_sinks
    - comment_references
    - constant_identifier_names
    - control_flow_in_finally
    - curly_braces_in_flow_control_structures
    - depend_on_referenced_packages
    - deprecated_consistency
    - diagnostic_describe_all_properties
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - file_names
    - no_duplicate_case_values
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors_in_immutables
    - prefer_const_literals_to_create_immutables