name: condorsmotors
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.65.0
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  mobile_scanner: ^3.5.6
  shared_preferences: ^2.5.2
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

# Configuración de íconos en la raíz, no dentro de flutter:
flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/condor-motors-logo.webp"
  adaptive_icon_background: "#1A1A1A"
  adaptive_icon_foreground: "assets/images/condor-motors-logo.webp"
  remove_alpha_ios: false
  windows:
    generate: true
    image_path: "assets/images/condor-motors-logo.webp"
  web:
    generate: true
    image_path: "assets/images/condor-motors-logo.webp"

flutter:
  uses-material-design: true

  assets:
    - assets/images/condor-motors-logo.webp
    # ... otros assets ...

  fonts:
    - family: Apercu
      fonts:
        - asset: assets/fonts/apercu_regular_pro.otf
          weight: 400
          style: normal
        - asset: assets/fonts/apercu_regular_italic_pro.otf
          weight: 400
          style: italic
        - asset: assets/fonts/apercu_medium_pro.otf
          weight: 500
        - asset: assets/fonts/apercu_medium_italic_pro.otf
          weight: 500
          style: italic
        - asset: assets/fonts/apercu_bold_pro.otf
          weight: 700
        - asset: assets/fonts/apercu_bold_italic_pro.otf
          weight: 700
          style: italic
