name: condorsmotors
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.70.2
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  mobile_scanner: ^6.0.7
  shared_preferences: ^2.5.2
  logging: ^1.3.0
  google_fonts: ^6.2.1
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.4
  font_awesome_flutter: ^10.8.0
  material_design_icons_flutter: ^7.0.7296
  intl: ^0.20.2
  msix: ^3.16.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

# Configuración de íconos en la raíz, no dentro de flutter:
flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/condor-motors-logo.webp"
  adaptive_icon_background: "#1A1A1A"
  adaptive_icon_foreground: "assets/images/condor-motors-logo.webp"
  remove_alpha_ios: false
  windows:
    generate: true
    image_path: "assets/images/condor-motors-logo.webp"
  web:
    generate: true
    image_path: "assets/images/condor-motors-logo.webp"

# Configuración para el instalador MSIX de Windows
msix_config:
  display_name: Condor Motors
  publisher_display_name: Tu Empresa
  identity_name: com.tuempresa.condorsmotors
  msix_version: 1.0.0.0
  logo_path: assets/images/condor-motors-logo.webp
  capabilities: internetClient

flutter:
  uses-material-design: true

  assets:
    - assets/images/condor-motors-logo.webp
    - assets/json/inventario_admin/stockProducts.json
    # ... otros assets ...

  fonts:
    - family: Apercu
      fonts:
        - asset: assets/fonts/apercu_regular_pro.otf
          weight: 400
          style: normal
        - asset: assets/fonts/apercu_regular_italic_pro.otf
          weight: 400
          style: italic
        - asset: assets/fonts/apercu_medium_pro.otf
          weight: 500
        - asset: assets/fonts/apercu_medium_italic_pro.otf
          weight: 500
          style: italic
        - asset: assets/fonts/apercu_bold_pro.otf
          weight: 700
        - asset: assets/fonts/apercu_bold_italic_pro.otf
          weight: 700
          style: italic
